import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import { BrowserProvider } from "ethers";
import { ProviderProvider } from "@/Functions/Contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <ProviderProvider>

        <body className={inter.className}>{children}</body>

      </ProviderProvider>

    </html>
  );
}
